title: Ben Orrin
email: ben@orrin.uk
description: >- # this means to ignore newlines until "baseurl:"
  Software developer, tea drinker and all round nerd.
  This is my home on the web.
baseurl: "" # the subpath of your site, leave empty if not needed
url: "https://orrin.uk" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

collections:
  projects:
    output: true
    permalink: /projects/:name/
  portfolio:
    output: true
    permalink: /portfolio/:name/